### ISSUE TITLE
Event Configuration

### ISSUE THREAD

**Issue by Skullians** [smashyalts/CrowdControlled#10]
Configuration for events.

```yaml
# Placeholders: see TODO WIKI LINK
Events:
  EVENT:
    platform: ["twitch", "youtube", "kick"] # You can specify events to trigger for multiple platforms, if applicable.
    on: ["sub", "donate"] # See TODO WIKI LINK for the possible triggers
    broadcast: true
    action: "modify_attribute" # See TODO WIKI LINK for possible actions
    values:
      attribute_type: "size" # If modifying attributes, what attribute should be modified?
      attribute_modifier: 1 # If modifying attributes, how to modify them (- for decreases!)

      name: "%viewer_name%" # If the action is an item, entity, etc, what should the name be. Supports Color Codes.
      entity: "BABY_ZOMBIE" # If an entity, what type of entity.
      invulnerable: false # Should the entitiy be invincible?

      item: "ROTTEN_FLESH" # If an item, what should the item be?
      count: 16 # If an item, what should the count be?
      lore: # If an item, what should the lore be? Supports multiple lines and color codes.
        - "&a%viewer_name%&e gifted &a%gift_count%"
        - "&agifts! &eThanks!"

      commands: # If the action is set to 'command', what will the commands be? Supports multiple commands (in order)!
        - "tp %streamer_ign% ~ 100 ~"
```
